development: &default
  adapter: mysql2
  #encoding: utf8
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  database: blog
  pool: 8
  username: root
  password: 1234567
  host: 127.0.0.1
  port: 3306

test:
  <<: *default

production:
  <<: *default